### ISSUE TITLE
Article RefugeesWork

### ISSUE THREAD

**Issue by IngaSchroeder** [RefugeesWork/organization#20]
https://github.com/RefugeesWork/organization/blob/master/Text%20RefugeesWork.odt 

possible article to be published --> please give feedback, add something

**TODO:**
* [x] read everything
* [x] give feedback on yellow section
* [x] give feedback on red sections
* [x] write the summary here below in the comments

**Comment by serapath** [comment]
* `"new power tool"` could be `"literacy of the future"`
* `professionellen Skills im Bereich....` would be `Digital Design`
* facebook group has ~600 peope and squatup facebook group has ~1100 people
* `...und
sind dabei nicht zwangsläufig auf deutsche Firmen angewiesen.` could be `..in addition use their middle east and other contacts to work remote as translators or sales people who can speak arabic`
* RED `i want to work` would be replaced with `I want to join the self employment program`
*currently, but change over time: BEREICHEN:
  * `MEDIA`, `

**Comment by deuxtan** [comment]
https://docs.google.com/document/d/1e4ttV5faSiBOA-Anc-5eJ3XY5jWYcMz5hKV75zAf2ak/edit?usp=sharing

**Comment by serapath** [comment]
@IngaSchroeder great - just read the article again:
https://github.com/RefugeesWork/organization/blob/master/refugeeswork%20text%20latest%20version.pdf

...and it feels pretty good :-)
awesome!
